Add a README.md file to the backup directory
JackGruber/joplin-plugin-backup pull request #70
Opened 2024-02-07 19:21 UTC by personalizedrefrigerator

# Summary

Adds a README.md file to the root backup directory that links to Simple Backup's README.

# To-do

- [ ] Add an automated test

2024-02-07 19:22 UTC, personalizedrefrigerator commented on src/locales/en_US.json
> +  "backupReadme": "# Joplin Backup\n\nThe backups in this folder were created with the Simple Backup plugin for Joplin. The most recent backup was created on %s.\n\nSee the [Simple Backup documentati
Alternatively, to link to GitHub:
```suggestion
  "backupReadme": "# Joplin Backup\n\nThe backups in this folder were created with the Simple Backup plugin for Joplin. The most recent backup was created on %s.\n\nSee the [Simple Backup documentation](https://github.com/JackGruber/joplin-plugin-backup?tab=readme-ov-file#restore) for information about how to restore from this backup.",
```

2024-02-17 10:59 UTC, JackGruber commented
We should then also write a test for the revisions and the README.md location

2024-02-17 11:07 UTC, JackGruber requested changes

2024-02-18 17:37 UTC, merged

2024-02-18 17:39 UTC, JackGruber commented
Thanks, I have added the German translation and removed the timestamp from the README, as this information is not meaningful if several profiles are backuped.